--install some plugins
local vim = vim
local Plug = vim.fn['plug#']
-- call plug#begin(stdpath('config') . '/plugged')
vim.call('plug#begin')
Plug('junegunn/fzf', { ['dir'] = '~/.fzf' })
Plug('junegunn/fzf', { ['do'] = function()
  vim.fn['fzf#install']()
end })
Plug('vim-airline/vim-airline')
Plug('vim-airline/vim-airline-themes')
Plug('ryanoasis/vim-devicons')
Plug('rakr/vim-one')
Plug('dense-analysis/ale')
Plug('tpope/vim-fugitive')
Plug('vim-test/vim-test')
Plug('mhinz/vim-startify')
Plug('neoclide/coc.nvim', { ['branch'] = 'release' })
Plug('lukas-reineke/indent-blankline.nvim', { ['tag'] = 'v2.20.8'})
Plug('nvim-treesitter/nvim-treesitter')
Plug('kshenoy/vim-signature')
Plug('nvim-lua/plenary.nvim')
Plug('nvim-neo-tree/neo-tree.nvim')
Plug('nvim-tree/nvim-web-devicons')
Plug('MunifTanjim/nui.nvim')
Plug('lewis6991/gitsigns.nvim')
Plug('ibhagwan/fzf-lua', { ['branch'] = 'main'})
vim.call('plug#end')
